version: '3.8'

services:
  authapi:
    build: ./authapi
    ports:
      - "9000:9000"
    networks:
      - social-network

  socialapi:
    build: ./socialapi
    ports:
      - "3500:3500"
    depends_on:
      - authapi
    networks:
      - social-network

networks:
  social-network:
